# Use an official Node.js runtime image
FROM node:14-slim

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the frontend dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port the frontend is running on
EXPOSE 3000

# Set the command to run the frontend
CMD ["npm", "run", "dev" ,"--", "--port", "3000"]